### ISSUE TITLE
Add HTTPS enforcement to pwndevils.com

### ISSUE THREAD

**Issue by blatayue** [pwndevils/pwndevils.github.io#1]
**Cloudflare no longer required,**
https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site
Your A records will need to be updated as well for the enforcement to work
 
https://www.troyhunt.com/heres-why-your-static-website-needs-https/

**Comment by adamdoupe** [comment]
Done! Thanks @blatayue !
https://pwndevils.com/
